server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # Caché fuerte para funcionar sin internet
  location ~* \.(js|css|png|jpg|svg|ico)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  # Soporte para SPA (rutas amigables)
  location / {
    try_files $uri $uri/ /index.html;
  }
}
